### PR TITLE
downloads latest ffmepg builds (resolves #8)

### LINKED ISSUE #8: Update
You should change the url's in your install.js to use always up to date links not static links that never update.
Your ffmpeg is a year old and almost all discord bots using discord.js use voice use your ffmpeg-binaries module.

### PR DESCRIPTION
**Pull request by favna**
As requested in #8 , this ensures that the install always downloads the latest ffmpeg builds for the proper platform and architecture

### CODE REVIEW

**Comment by favna** [comment]
@ShayBox please review the URLs and code to confirm I did it correctly

**Comment by ShayBox** [comment]
👍 Looks good
Good luck getting it merged, the dev hasn't been active for months :(

**Comment by Hackzzila** [comment]
I could not get this to work. You will need some library to handle zip files and xz compression. Also, you should then be able to delete the darwin, linux, and windows folders.

**Comment by favna** [comment]
Dammit sorry I miss licked on the mobile app

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by favna** [comment]
Misclicked*

Anyway I’ll look into working with zips and tar balls across operating systems when I have more time. Right now I’m focusing on my own discord bot and adding a casino commands group which is more work than what it may sound like when doing it properly

**Comment by Hackzzila** [comment]
Resolved in 009e4d540aa5bda01cc6781b9f1d1c682260c2ef

**Pull request closed without merging**
